// <auto-generated />
namespace mvcformsauthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mvc5book_musicclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mvc5book_musicclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081725520_mvc5book_musicclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
